---
- name: Install Software related to gaming, and a bunch of FOSS games.
  hosts: localhost
  connection: local
  become: true

  tasks:
    # This seems a bit of a crime but it works:
    # The long-ass regex will capture both lines at once, so there will only ever be one match
    # and then simply replaces the match with the content of the 2 capture groups
    # (uncommented line 1 +\n) and (uncommented line 2)
    # See example at the bottom for more:
    - name: Enable 32-bit libraries
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: '(?m)^#\S*(\[multilib\]\n?)#\S*(Include = /etc/pacman\.d/mirrorlist)$'
        replace: '\g<1>\g<2>'

    - name: Update the repos
      community.general.pacman:
        update_cache: true

    # - name: "Install common graphics libraries"
    #   community.general.pacman:
    #     name:
    #       # - mesa is assumed to be installed
    #       - lib32-mesa
    #       - vulkan-icd-loader
    #       - lib32-vulkan-icd-loader
    #     state: latest
    #     extra_args: --needed --noconfirm

    # - name: "Install NVIDIA-specific software (Proprietary driver)"
    #   community.general.pacman:
    #     name:
    #     # - nvidia/nvidia-lts is assumed to be installed
    #       - nvidia-utils
    #       - lib32-nvidia-utils
    #       - nvidia-settings
    #     state: latest
    #     extra_args: --needed --noconfirm
    #   when: (hostvars.graphics == 'nvidia')

    # - name: "Install AMD-specific software"
    #   community.general.pacman:
    #     name:
    #       # - mesa is assumed to be installed
    #       - vulkan-radeon
    #       - lib32-vulkan-radeon
    #     state: latest
    #     extra_args: --needed --noconfirm
    #   when: (hostvars.graphics == 'amd')

    # # Full vilkan support only exists in Skylake or newer (Intel iX-6000 series)
    # - name: "Install Intel-specific software"
    #   community.general.pacman:
    #     name:
    #       # - mesa is assumed to be installed
    #       - vulkan-intel
    #       - lib32-vulkan-intel
    #     state: latest
    #     extra_args: --needed --noconfirm
    #   when: (hostvars.graphics == 'amd')

    - name: "Install gaming software (from official repos)"
      community.general.pacman:
        name:
          - steam
          - lutris
          - mangohud
        state: latest
        extra_args: --needed --noconfirm

    - name: Install wine # This is a separate task bc all the other wine bullshit is installed as a dependency.
      community.general.pacman:
        name:
          - wine-staging
          - winetricks
        state: latest
        extra_args: --needed --noconfirm

    - name: Install wine and lutris dependencies
      community.general.pacman:
        name:
          - alsa-lib
          - alsa-plugins
          - fluidsynth # MIDI support
          # - gamemode
          - giflib
          - gnutls
          - gst-plugins-base-libs
          - gtk3
          - innoextract # Extract Inno Setup installers
          - lib32-alsa-lib
          - lib32-alsa-plugins
          # - lib32-gamemode
          - lib32-giflib
          - lib32-gnutls
          - lib32-gst-plugins-base-libs
          - lib32-gtk3
          - lib32-libpulse
          - lib32-libva
          - lib32-libxcomposite
          - lib32-mangohud
          - lib32-ocl-icd
          - lib32-sdl2
          - lib32-sqlite
          - lib32-v4l-utils
          - lib32-vkd3d # DirectX 12 support
          - lib32-vulkan-icd-loader # Vulkan support
          - libayatana-appindicator # tray icon support
          - libpulse
          - libva
          - libxcomposite
          - ocl-icd
          - python-protobuf # Battle.net support
          - sdl2
          - sqlite
          - v4l-utils
          - vkd3d # DirectX 12 support
          - vulkan-icd-loader # Vulkan support
          - vulkan-tools # Vulkan support
        state: latest
        reason: dependency
        extra_args: --needed --noconfirm

    - name: Install gaming software (from the AUR)
      kewlfft.aur.aur:
        use: yay
        name:
          - heroic-games-launcher-bin
          - protontricks
      become: false

    - name: Install FOSS games
      community.general.pacman:
        name:
          - angband
          - cataclysm-dda
          - cataclysm-dda-tiles
          - crawl-ncurses
          - openra
          - supertuxkart
          - xonotic
          - ppsspp
          - quadrapassel
        state: latest
        extra_args: --needed --noconfirm

    - name: Install FOSS games (from the AUR)
      kewlfft.aur.aur:
        use: yay
        name:
          - oolite
          - openarena
          - urbanterror
          - gzdoom-bin
          - pioneer-bin
          - the-dark-mod-bin
          - gearhead
      become: false
# Other things to untall
# - Latex
# - CUPS
# - Gaming playbook (wine deps, steam lutris mangohud)
# - Open source gmaes

# Un-commenting line example.
# Can take multiple line with loop, but each line but be standalone, and is replaced only once.
# - name: Uncomment shit
#   lineinfile:
#     path: /etc/randomfile
#     regexp: '^#+\s*{{ item.key }}\s'
#     line: "{{ item.key }} {{ item.value }}"
#   with_items:
#   - key: FunnyNumber
#     value: 69
#   - key: BestGirl
#     value: Hemiru
