---
- hosts: localhost
  connection: local
  become: true
  roles:
    - { role: gather_facts, become: false }
    - { role: install_packages, become: true }
    - { role: setup_aur, become: false }
    - { role: install_aur_packages, become: false }
    - { role: clone_repos, become: false }
    - { role: setup_homedir, become: false }
    - { role: stow_config_files, become: false }
    - { role: setup_st, become: false }
    - { role: setup_dmenu, become: false }
    - { role: setup_slstatus, become: false }
    - { role: setup_dwm, become: false }
    - { role: setup_services, become: true }
