---
  - name: stow bashrc
    shell: stow -v bash -t /home/{{ remote_regular_user }}
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dotfiles
    when: (not bash_link.stat.exists) or (not bash_link.stat.islnk)

  - name: stow vimrc
    shell: stow -v vim -t /home/{{ remote_regular_user }}
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dotfiles
    when: (not vim_link.stat.exists) or (not vim_link.stat.islnk)

  - name: stow picom
    command: stow -v picom -t /home/{{ remote_regular_user }}
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dotfiles
    creates: /home/{{ remote_regular_user }}/.config/compton/compton.conf

  - name: stow Xresources
    command: stow -v Xresources -t /home/{{ remote_regular_user }}
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dotfiles
    creates: /home/{{ remote_regular_user }}/.Xresources

  - name: stow mpv
    command: stow -v mpv -t /home/{{ remote_regular_user }}
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dotfiles
    creates: /home/{{ remote_regular_user }}/.config/mpv/input.conf

  - name: stow ranger
    command: stow -v ranger -t /home/{{ remote_regular_user }}
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dotfiles
    creates: /home/{{ remote_regular_user }}/.config/ranger/rc.conf

  - name: stow tmux
    command: stow -v tmux -t /home/{{ remote_regular_user }}
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dotfiles
    creates: /home/{{ remote_regular_user }}/.tmux.conf

 
  - import_tasks:
      file: setup-omzsh.yml