---
- name: Compile slstatus
  ansible.builtin.command: make
  args:
    chdir: /home/{{ remote_regular_user }}/GithubRepos/slstatus-build

- name: Install slstatus
  ansible.builtin.command: make install
  args:
    chdir: /home/{{ remote_regular_user }}/GithubRepos/slstatus-build
  become: true

- name: Compile slstatus
  ansible.builtin.command: make
  args:
    chdir: /home/{{ remote_regular_user }}/GithubRepos/slstatus-build
