---
  - name: Copy dwm.desktop so it shows up in lightdm
    copy:
      src: dwm.desktop
      dest: /usr/share/xsessions/
      owner: root
      group: root
      mode: "0644"

  - name: make .dwm folder
    file: 
      path: /home/{{ remote_regular_user }}/.dwm 
      state: directory
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0700"

  - name: copy over autostart config file
    template: 
      src: autostart.j2
      dest: /home/{{ remote_regular_user }}/.dwm/
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0744"


  - name: setup pywall for dwm
    copy:
      src: colors.Xresources
      dest: /home/{{ remote_regular_user }}/.config/wal/templates/
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0644"

  - name: pick a random wallpaper
    command: ls -l /home/{{ remote_regular_user }}/Pictures/std_wallpapers|awk 'NR>1 {print $NF}'
    register: wallpapers   

  - name: set a wallpaper with pywall at random
    command: wal -i {{wallpapers.stdout_lines|random}}
    register: wal
  - debug:
      msg: "wal output: {{wal.stdout}}"
