---
  - name: Copy dwm.desktop so it shows up in lightdm
    copy:
      src: dwm.desktop
      dest: /usr/share/xsessions/
      owner: root
      group: root
      mode: "0644"
  - name: make .dwm folder
    file: 
      path: /home/{{ remote_regular_user }}/.dwm 
      state: directory
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0700"

  ### Make .dwm/autostart.sh here from template

  - name: setup pywall for dwm
    copy:
      src: colors.Xresources
      dest: /home/{{ remote_regular_user }}/.config/wal/templates/
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0644"

        # Copy over wallpapers
        # run pywall once to generate colorscheme
        #
        # Compile DWM, either here or in a separate role
