---
- name: Enable systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    enabled: true
    state: started

- name: Tell NetworkManager to use systemd-resolved
  ansible.builtin.copy:
    src: files/dns.conf
    dest: /etc/NetworkManager/conf.d/dns.conf
    owner: root
    group: root
    mode: '0644'

- name: Symlink /etc/resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Enable NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    enabled: true
    state: restarted

- name: Enable LightDM
  ansible.builtin.service:
    name: lightdm
    enabled: true
    state: started

- name: Enable TLP
  ansible.builtin.service:
    name: tlp
    enabled: true
    state: started

- name: Enable Bluetooth
  ansible.builtin.service:
    name: bluetooth
    enabled: true
    state: started

- name: Enable lm_sensors
  ansible.builtin.service:
    name: lm_sensors
    enabled: true
    state: started

- name: Enable Polkit
  ansible.builtin.service:
    name: polkit
    enabled: true
    state: started
