---
- name: Refresh repos
  community.general.pacman:
    update_cache: true

- name: Remove VIM (so we can install gvim)
  community.general.pacman:
    name: vim
    state: absent

- name: Install base packages
  community.general.pacman:
    name:
      - xorg-server
      - xorg-xinit
      - lightdm # Login manager of choice
      - lightdm-slick-greeter # The default ui sucks so we have this one
      - xfce4
      - xfce4-goodies
      - pavucontrol # probably wrong, does it support pipewire?
      - gvim
      - git
      - stow # Necessary to sim-link dotfiles into place
      - openssh
      - curl
      - wget
      - man-pages
      - ttf-ubuntu-font-family
      - noto-fonts
      - noto-fonts-cjk # Japanese/Korean font
      - noto-fonts-emoji # Emoji font
      - ttf-droid
      - ttf-dejavu
      - ttf-hack # Technically pointless since we always the nerd-font version
      - ttf-hack-nerd
      - ttf-font-awesome # Used mainly for slstatus icons, i think
      - xdg-user-dirs
      - xdg-user-dirs-gtk
      - alacritty # Backup terminal, just in case
      - python-pip
      - vim-powerline
      - powerline-fonts # This might actually be redundant with nerd-font
      - zsh
      - zsh-autosuggestions
      - zsh-completions
      - zsh-lovers
      - tig
      - gitui
      - meld # Its here because we set it as default git difftool/mergetools
      - bluez
      - blueman
      - ristretto
      - mpv
      - fastfetch
      - arandr
      - net-tools
      - networkmanager
      - dhcpcd
      - tlp # Power management on laptops.
      - htop
      - gparted
      - gpart # Recover corrupted MBR partition tables with GParted
      - btrfs-progs # support reading BTRFS
      - dosfstools # support reading FAT16/FAT32
      - exfatprogs # support reading exFAT
      - f2fs-tools # supports reading f2fs (that one SSD FS)
      - ntfs-3g # See note at the bottom!
      - mtools # Support reading DOS file systems (whatever that means)
      - rsync
      - lm_sensors # Enable use of temperature sensors, will error out in VBox
      - engrampa # GUI archive manager
      - unace # ACE support in engranpa
      - unrar # RAR support in engranpa
      - p7zip # 7z and ARJ support in engranpa
      - zip # Already an ngranpa dependency
      - unzip # Already an ngranpa dependency
      - cpio # Supports a bunch new formats, including RPM
      - lrzip
      - squashfs-tools
      - pv
    state: latest
    extra_args: --needed --noconfirm

- name: Install packages needed by dwm
  community.general.pacman:
    name:
      - base-devel # Also needed to compile yay
      - python-pywal
      - picom
      - xsettingsd # Allows GUI apps in dwm to still have theming
      - network-manager-applet
      - redshift
      - xorg-server-devel
      - xorg-setxkbmap
      - xorg-xinit
      - xorg-xbacklight
      - xorgproto
      - xorg-xkill
      - light-locker
      - gnome-keyring
      - pamixer
      - firefox
      - feh
      - keepassxc
      - thunderbird
      - thunar # Technically already installed by xfce-goodies, i think
      - thunar-archive-plugin
      - gvfs
      - thunar-media-tags-plugin
      - thunar-volman
      - catfish # Same as above
      - tumbler
      - cmus
      - calcurse
      - mate-calc
      - maim
      - notify-osd
      - trash-cli
      - atool
      - highlight
      - polkit-gnome
      - zathura
      - zathura-pdf-mupdf
      - zathura-cb
      - zathura-djvu
      - zathura-ps
    state: latest
    extra_args: --needed --noconfirm

- name: Gather package facts # Gets a list of crrently installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Install pulseaudio if no audio system is present.
  ansible.builtin.package:
    name: pulseaudio
    state: present
  when: "'pipewire-pulse' not in ansible_facts.packages and 'pulseaudio' not in ansible_facts.packages"

# ABOUT THE NTFS SITUATION
# ========================
# There are 2 drivers in Arch to support NTFS:
#
# 1) NTFS-3G. Older, more limited support. Provides driver + userspace utils
#
# 2) Built-in driver: Newer, comes with all (arch) kernels since 5.15
# However it has no userspace utilities, so we still to rely on ntfs-3g for that.
#
# Source: https://wiki.archlinux.org/title/NTFS
