---
- name: Check if the expected values are set
  ansible.builtin.debug:
    msg: Value of remote_regular_user is {{ remote_regular_user }}. Its group is {{ remote_regular_user_group }}
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    create_home: true
    name: aur_builder
#      group: aur_builder

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.copy:
    src: files/11-aur_builder
    dest: /etc/sudoers.d/11-aur_builder
    owner: root
    group: root
    mode: '0440'

- name: Create temporary build folder
  ansible.builtin.file:
    path: /home/aur_builder/.tmp
    state: directory
    owner: aur_builder
    group: aur_builder
    mode: "0755"
  become: true
  become_user: aur_builder

- name: Clone yay # noqa: latest
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: /home/aur_builder/.tmp/yay
    clone: true
  become: true
  become_user: aur_builder
  when: not yay_location.stat.exists

- name: Make Yay
  ansible.builtin.command: makepkg --needed -Acs --noconfirm
  args:
    chdir: /home/aur_builder/.tmp/yay
    creates: "*.pkg.tar.zst"
  become: true
  become_user: aur_builder
  when: not yay_location.stat.exists

- name: Install Yay
  ansible.builtin.command: makepkg -i --noconfirm
  args:
    chdir: /home/aur_builder/.tmp/yay
    creates: "/usr/bin/yay"
  become: true
  become_user: aur_builder
  when: not yay_location.stat.exists
