---
  - name: Create bin home folder
    file:
      path: /home/{{ remote_regular_user }}/bin
      state: directory
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0755"

  - name: copy scripts to home/bin folder
    copy:
      src: /home/{{ remote_regular_user }}/GithubRepos/dotfiles/bin/
      dest: /home/{{ remote_regular_user }}/bin/
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0700"

  - name: allow local user to run some commands without sudo pw, so that scripts will work
    become: true
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/12-{{ remote_regular_user }}
      line: '%wheel ALL=(ALL:ALL) NOPASSWD: /usr/bin/poweroff, /usr/bin/reboot, /usr/bin/shutdown, /usr/bin/systemctl'
      create: yes
      validate: 'visudo -cf %s'
  - debug:  
        msg: "Created file is called 12-{{ remote_regular_user }}" 

  - name: Delete existing bash files
    file:
      path: '{{ item }}'
      state: absent
    with_items:
      - /home/{{ remote_regular_user }}/.bashrc
      - /home/{{ remote_regular_user }}/.bash_profile
    when: (bash_link.stat.exists) and (not bash_link.stat.islnk)

  - name: Delete existing .vimrc
    file:
      path: /home/{{ remote_regular_user }}/.vimrc
      state: absent
    when: (vim_link.stat.exists) and (not vim_link.stat.islnk)
  
  - name: Create folders in home if they don't exist
    command: xdg-user-dirs-update
    args:
      creates: /home/{{ remote_regular_user }}/.icons

  - name: make wallpaper folder
    file: 
      path: /home/{{ remote_regular_user }}/Pictures/std_wallpapers 
      state: directory
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0700"

  - name: copy over wallpapers
    copy:
      src: files/
      dest: /home/{{ remote_regular_user }}/Pictures/std_wallpapers 
      owner: "{{ remote_regular_user }}"
      group: "{{ remote_regular_user_group }}"
      mode: "0644"
      # directory_mode: true
      # remote_src: true
    # with_fileglob:
      # - "*.png"
      # - "*.jpg"
