---
  - name: compile dmenu
    command: make
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dmenu-build
  - name: Install dmenu
    command: make install
    args:
      chdir: /home/{{ remote_regular_user }}/GithubRepos/dmenu-build
    become: true
