--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/elendil/Pictures/std_wallpapers/saber.jpg"

-- Special
background="#090b1b"
foreground="#f5e5c6"
cursor="#f5e5c6"

-- Colors
color0="#090b1b"
color1="#D46254"
color2="#D9A857"
color3="#F49E68"
color4="#6C438E"
color5="#B96492"
color6="#E89C90"
color7="#f5e5c6"
color8="#aba08a"
color9="#D46254"
color10="#D9A857"
color11="#F49E68"
color12="#6C438E"
color13="#B96492"
color14="#E89C90"
color15="#f5e5c6"
