foreground   #f5e5c6
background   #090b1b
cursor       #f5e5c6

color0       #090b1b
color8       #aba08a
color1       #D46254
color9       #D46254
color2       #D9A857
color10      #D9A857
color3       #F49E68
color11      #F49E68
color4       #6C438E
color12      #6C438E
color5       #B96492
color13      #B96492
color6       #E89C90
color14      #E89C90
color7       #f5e5c6
color15      #f5e5c6
