# Shell variables
# Generated by 'wal'
wallpaper='/home/elendil/Pictures/std_wallpapers/saber.jpg'

# Special
background='#090b1b'
foreground='#f5e5c6'
cursor='#f5e5c6'

# Colors
color0='#090b1b'
color1='#D46254'
color2='#D9A857'
color3='#F49E68'
color4='#6C438E'
color5='#B96492'
color6='#E89C90'
color7='#f5e5c6'
color8='#aba08a'
color9='#D46254'
color10='#D9A857'
color11='#F49E68'
color12='#6C438E'
color13='#B96492'
color14='#E89C90'
color15='#f5e5c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
