---
- name: Stow Xresources
  ansible.builtin.command: stow -v Xresources -t /home/{{ remote_regular_user }}
  args:
    chdir: /home/{{ remote_regular_user }}/GithubRepos/dotfiles
    creates: /home/{{ remote_regular_user }}/.Xresources

- name: Compile ST
  ansible.builtin.command: make
  args:
    chdir: /home/{{ remote_regular_user }}/GithubRepos/st-build
    creates: st

- name: Install ST
  ansible.builtin.command: make install
  args:
    chdir: /home/{{ remote_regular_user }}/GithubRepos/st-build
    creates: /usr/local/bin/st
  become: true

- name: Cleanup
  ansible.builtin.command: make clean
  args:
    chdir: /home/{{ remote_regular_user }}/GithubRepos/st-build
    removes: config.h
